import React, { Component } from "react";
// import { Link } from "react-router-dom";
import "../TermsOfServices/TermsOfServices.scss";
class PrivacyPolicy extends Component {
    render() {
        return (
            <section className="gb-tems-block">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-10 offset-lg-1">
                            <h1>Goodbit Privacy Policy</h1>
                            <span className="gb-terms-date">Effective Date: September 18, 2018</span>

                            <p>Goodbit, PBC ("us", "we", or "our") operates the https://www.goodbit101.com website and all of the website’s sub-domains (together, the "Service").</p>
                            <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
                            <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms of Service.</p>
                            <p>This policy is incorporated into our Terms of Service as if fully set forth therein.</p>

                            <p className="mb-0">Definitions</p>
                            <p className="mb-0">Personal Data</p>
                            <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>

                            <p className="mb-0">Usage Data</p>
                            <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>

                            <p className="mb-0">Cookies</p>
                            <p>Cookies are small pieces of data stored on a User’s device.</p>

                            <p className="mb-0">Data Controller</p>
                            <p>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>

                            <p className="mb-0">Data Processor (or Service Providers)</p>
                            <p>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>

                            <p className="mb-0">Data Subject</p>
                            <p>Data Subject is any living individual who is the subject of Personal Data.</p>

                            <p className="mb-0">User</p>
                            <p>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>

                            <p className="mb-0">Information Collection and Use</p>
                            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                            <p>Types of Data Collected</p>


                            <p className="mb-0">Personal Data</p>
                            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
                            <ul className="gb-bullet">
                                <li>Email address</li>
                                <li>First name and last name</li>
                                <li>Phone number</li>
                                <li>Address, State, Province, ZIP/Postal code, City</li>
                                <li>Cookies and Usage Data</li>
                            </ul>

                            <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>

                            <p className="mb-0">Usage Data</p>
                            <p>We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, your time zone, what you clicked on pages, the time spent on pages, what websites or search terms referred you to the Service, unique device identifiers and other diagnostic data.</p>

                            <p className="mb-0">Tracking Cookies Data</p>
                            <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device.</p>
                            <p>We also use log files, web beacons, tags, pixels, scripts and similar tracking technologies to collect and track information and to improve and analyze our Service.</p>
                            <p>Log files track actions occurring on the Service, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.</p>
                            <p>Web beacons, tags, pixels and scripts are electronic files used to record information about how you browse the Service.</p>
                            <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

                            <p className="mb-0">Examples of Cookies we use:</p>
                            <ul className="gb-bullet">
                                <li>Session Cookies. We use Session Cookies to operate our Service.</li>
                                <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
                                <li>Security Cookies. We use Security Cookies for security purposes.</li>
                                <li>Advertising Cookies. Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
                            </ul>

                            <p className="mb-0">You can learn more about cookies at the following third-party websites:</p>
                            <p className="mb-0">AllAboutCookies: <a href="http://www.allaboutcookies.org/" target="_blank" rel="noopener noreferrer">http://www.allaboutcookies.org</a></p>
                            <p>Network Advertising Initiative: <a href="http://www.networkadvertising.org/" target="_blank" rel="noopener noreferrer">http://www.networkadvertising.org </a></p>

                            <p className="mb-0">Use of Data</p>
                            <p className="mb-0">We use the collected data for various purposes:</p>
                            <ul className="gb-bullet">
                                <li>To provide and maintain our Service</li>
                                <li>To notify you about changes to our Service</li>
                                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                                <li>To provide customer support</li>
                                <li>To gather analysis or valuable information so that we can improve our Service</li>
                                <li>To monitor the usage of our Service</li>
                                <li>To detect, prevent and address technical issues</li>
                                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already used, purchased or inquired about unless you have opted not to receive such information</li>
                            </ul>

                            <p className="mb-0">Retention of Data</p>
                            <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>

                            <p>We will also retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                            <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

                            <p className="mb-0">Transfer of Data</p>
                            <p>Your information, including Personal Data, is processed at our operating offices and in any other locations where the parties involved in the processing are located.</p>

                            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
                            <p>If you are located outside the United States of America and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States of America and process it there.</p>
                            <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                            <p>We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>


                            <p className="mb-0">Disclosure of Data</p>
                            <p className="mb-0">Business Transaction</p>
                            <p>If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

                            <p className="mb-0">Disclosure for Law Enforcement</p>
                            <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

                            <p className="mb-0">Legal Requirements</p>
                            <p className="mb-0">We may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
                            <ul className="gb-bullet">
                                <li>To comply with a legal obligation</li>
                                <li>To protect and defend our rights or property </li>
                                <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                                <li>To protect the personal safety of users of the Service or the public</li>
                                <li>To protect against legal liability</li>
                            </ul>

                            <p className="mb-0">Security of Data</p>
                            <p>We take appropriate security measures to prevent unauthorized disclosure, access, modification, or destruction of the data. The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data and other data (including SSL encryption), we cannot guarantee its absolute security. In addition, we have no control over the security of other web sites on the internet that you might visit even when a link may appear to those web sites from our Service.</p>

                            <p className="mb-0">"Do Not Track" Signals</p>
                            <p>We do not support Do Not Track ("DNT") requests. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

                            <p className="mb-0">Your Rights</p>
                            <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
                            <p>Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes.</p>
                            <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us through the contact information below.</p>

                            <p className="mb-0">In certain circumstances, you have the right:</p>
                            <ul className="gb-bullet">
                                <li>To access and receive a copy of the Personal Data we hold about you</li>
                                <li>To rectify any Personal Data held about you that is inaccurate</li>
                                <li>To request the deletion of Personal Data held about you</li>
                            </ul>

                            <p>You have the right to data portability for the information you provide to us. You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you can manage and move it. Please note that we may ask you to verify your identity before responding to such requests.</p>
                            <p>If you are a European resident, you have the right to access personal information we hold about you and to ask that your personal information be corrected, updated, or deleted. If you would like to exercise this right, please contact us through the contact information below. Additionally, if you are a European resident, you have the right to withdraw your consent to the processing of your Personal Data at any time and the right to object to the processing of your data. If you would like to exercise any of these rights, please contact us through the contact information below. Additionally, if you are a European resident we note that we are processing your information in order to fulfill a contact request from you (for example, if you use a contact form on the Service or otherwise contact us), or otherwise to pursue our legitimate business interests listed above. Additionally, please note that your information will be transferred outside of Europe, including to Canada and the United States of America.</p>

                            <p className="mb-0">Service Providers</p>
                            <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
                            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

                            <p className="mb-0">Analytics</p>
                            <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

                            <p className="mb-0">Google Analytics</p>
                            <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network. You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity. You can also opt-out of Google Analytics here <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout</a>. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener noreferrer">http://www.google.com/intl/en/policies/privacy</a>.</p>

                            <p>Mixpanel <a href="http://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener noreferrer">http://www.google.com/intl/en/policies/privacy/</a> Mixpanel is provided by Mixpanel Inc. You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, please visit this page: <a href="https://mixpanel.com/optout/" target="_blank" rel="noopener noreferrer">https://mixpanel.com/optout/</a>. For more information on what type of information Mixpanel collects, please visit the Terms of Use page of Mixpanel: <a href="https://mixpanel.com/terms/" target="_blank" rel="noopener noreferrer">https://mixpanel.com/terms/</a>. For more information on the privacy practices of Mixpanel, please visit the Mixpanel Privacy Terms web page: <a href="https://mixpanel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">https://mixpanel.com/legal/privacy-policy</a>.</p>

                            <p className="mb-0">Visual Website Optimizer</p>
                            <p>Visual Website Optimizer is provided by Wingify. You can prevent Visual Website Optimizer from using your information for analytics purposes by opting-out. To opt-out of Visual Website Optimizer service, please visit this page: <a href="https://vwo.com/opt-out" target="_blank" rel="noopener noreferrer">https://vwo.com/opt-out</a>. For more information on what type of information Visual Website Optimizer collects, please visit the Terms of Use page of Visual Website Optimizer: <a href="https://vwo.com/terms-conditions/" target="_blank" rel="noopener noreferrer">https://vwo.com/terms-conditions/</a> . For more information on the privacy practices of Visual Website Optimizer, please visit the Visual Website Optimizer Privacy Terms web page: <a href="https://vwo.com/privacy-policy" target="_blank" rel="noopener noreferrer">https://vwo.com/privacy-policy</a>.</p>

                            <p className="mb-0">Hotjar</p>
                            <p>Hotjar is provided by Hotjar Ltd. You can prevent Hotjar from using your information for analytics purposes by opting-out. To opt-out of Hotjar service, please visit this page: <a href="https://www.hotjar.com/legal/compliance/opt-out" target="_blank" rel="noopener noreferrer">https://www.hotjar.com/legal/compliance/opt-out</a>. For more information on what type of information Hotjar collects, please visit the Terms of Use page of Hotjar: <a href="https://www.hotjar.com/legal/policies/terms-of-service" target="_blank" rel="noopener noreferrer">https://www.hotjar.com/legal/policies/terms-of-service</a>. For more information on the privacy practices of Hotjar, please visit the Hotjar Privacy Terms web page: <a href="https://www.hotjar.com/legal/policies/privacy" target="_blank" rel="noopener noreferrer">https://www.hotjar.com/legal/policies/privacy</a>.</p>

                            <p className="mb-0">Shareaholic</p>
                            <p>Shareaholic is provided by Shareaholic, Inc. You can prevent Shareaholic from using your information for analytics purposes by opting-out. To opt-out of Shareaholic service, please visit this page: <a href="https://www.shareaholic.com/privacy/choices" target="_blank" rel="noopener noreferrer">https://www.shareaholic.com/privacy/choices</a>. For more information on what type of information Shareaholic collects, please visit the Terms of Use page of Shareaholic: <a href="https://www.shareaholic.com/terms/" target="_blank" rel="noopener noreferrer">https://www.shareaholic.com/terms/</a>. For more information on the privacy practices of Shareaholic, please visit the Shareaholic Privacy Terms web page: <a href="https://www.shareaholic.com/privacy/" target="_blank" rel="noopener noreferrer">https://www.shareaholic.com/privacy/</a>.</p>

                            <p className="mb-0">Advertising</p>
                            <p>We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.</p>

                            <p className="mb-0">Google AdSense DoubleClick Cookie</p>
                            <p>Google, as a third party vendor, uses cookies to serve ads on our Service. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Service or other websites on the Internet. You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the Google Ads Settings web page: <a href="http://www.google.com/ads/preferences/" target="_blank" rel="noopener noreferrer">http://www.google.com/ads/preferences/</a>.</p>

                            <p className="mb-0">Bing</p>
                            <p>Bing is an advertising service provided by Microsoft Corporation. For more information about Bing, please visit their Privacy Policy: <a href="https://privacy.microsoft.com/en-us/privacystatement" target="_blank" rel="noopener noreferrer">https://privacy.microsoft.com/en-us/privacystatement</a>.</p>

                            <p className="mb-0">Amazon</p>
                            <p>Amazon is a service provided by Amazon.com, Inc. For more information about Amazon, please visit their Privacy Policy: <a href="https://www.amazon.com/gp/help/customer/display.html/ref=footer_privacy?ie=UTF8&nodeId.=468496" target="_blank" rel="noopener noreferrer">https://www.amazon.com/gp/help/customer/display.html/ref=footer_privacy?ie=UTF8&nodeId.=468496</a>.</p>

                            <p className="mb-0">Awin</p>
                            <p>Awin is an advertising service provided by AWIN Ltd. For more information about Awin, please visit their Privacy Policy: <a href="https://www.awin.com/gb/legal/privacy-policy" target="_blank" rel="noopener noreferrer"> https://www.awin.com/gb/legal/privacy-policy</a>.</p>

                            <p className="mb-0">Behavioral Remarketing</p>
                            <p>We use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.</p>

                            <p className="mb-0">Google AdWords</p>
                            <p>Google AdWords remarketing service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer"> http://www.google.com/settings/ads</a>. Google also recommends installing the Google Analytics Opt-out Browser Add-on - <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer"> https://tools.google.com/dlpage/gaoptout</a> - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener noreferrer" >http://www.google.com/intl/en/policies/privacy/</a>.</p>

                            <p className="mb-0">Twitter</p>
                            <p>Twitter remarketing service is provided by Twitter Inc. You can opt-out from Twitter's interest-based ads by following their instructions: <a href="https://support.twitter.com/articles/20170405" target="_blank" rel="noopener noreferrer">https://support.twitter.com/articles/20170405</a>. You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: <a href="https://twitter.com/privacy" target="_blank" rel="noopener noreferrer">https://twitter.com/privacy</a>.</p>

                            <p className="mb-0">Facebook</p>
                            <p>Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/164968693837950" target="_blank" rel="noopener noreferrer">https://www.facebook.com/help/164968693837950</a>. To opt-out from Facebook's interest-based ads follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217" target="_blank" rel="noopener noreferrer">https://www.facebook.com/help/568137493302217</a>. Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/" target="_blank" rel="noopener noreferrer">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/" target="_blank" rel="noopener noreferrer">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/" target="_blank" rel="noopener noreferrer">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings. For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: <a href="https://www.facebook.com/privacy/explanation" target="_blank" rel="noopener noreferrer">https://www.facebook.com/privacy/explanation</a>. For more information about how targeted advertising works, you can visit the Network Advertising Initiative’s (“NAI”) educational page at: <a href="http://www.networkadvertising.org/understanding-online-advertising/how-does-it-work" target="_blank" rel="noopener noreferrer">http://www.networkadvertising.org/understanding-online-advertising/how-does-it-work</a>.</p>
                            <p>Additionally, you can opt out of some of these services by visiting the Digital Advertising Alliance’s opt-out portal at: <a href="http://optout.aboutads.info/" target="_blank" rel="noopener noreferrer">http://optout.aboutads.info/</a>. </p>

                            <p className="mb-0">Payments</p>
                            <p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
                            <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
                            <p>The payment processors we work with are:</p>

                            <p className="mb-0">Stripe</p>
                            <p>Their Privacy Policy can be viewed at: <a href="https://stripe.com/us/privacy" target="_blank" rel="noopener noreferrer">https://stripe.com/us/privacy</a>.</p>

                            <p className="mb-0">PayPal or Braintree</p>
                            <p>Their Privacy Policy can be viewed at: <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" target="_blank" rel="noopener noreferrer">https://www.paypal.com/webapps/mpp/ua/privacy-full</a>.</p>

                            <p className="mb-0">Square</p>
                            <p>Their Privacy Policy can be viewed at: <a href="https://squareup.com/legal/privacy-no-account" target="_blank" rel="noopener noreferrer">https://squareup.com/legal/privacy-no-account</a>.</p>

                            <p className="mb-0">Emails</p>
                            <p>We use third-party services to manage our email marketing subscriber list and send emails to our subscribers. You can unsubscribe from our newsletter by clicking the unsubscribe link provided at the end of each newsletter. The services we work with are:</p>

                            <p className="mb-0">MailChimp</p>
                            <p>Their Privacy Policy can be viewed at: <a href="https://mailchimp.com/legal/privacy/" target="_blank" rel="noopener noreferrer">https://www.mailchimp.com/legal/privacy</a></p>

                            <p className="mb-0">Amazon AWS</p>
                            <p>Their Privacy Policy can be viewed at: <a href="https://aws.amazon.com/privacy/" target="_blank" rel="noopener noreferrer">https://www.aws.amazon.com/privacy</a></p>
                            <p>MailChimp ands Amazon AWS are third-party providers, which may process your data using industry standard technologies to help monitor and improve our newsletter.</p>

                            <p className="mb-0">Links to Other Sites</p>
                            <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

                            <p className="mb-0">Children's Privacy</p>
                            <p>Our Service does not address anyone under the age of 13 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

                            <p className="mb-0">Changes to This Privacy Policy</p>
                            <p>We reserve the right to update this Privacy Policy at any time by giving notice on this page and/or – if legally and technically feasible - sending a notice to you. You are advised to review this Privacy Policy often for any changes, referring to the "effective date" at the top of this Privacy Policy. Changes to this Privacy Policy are effective when they are posted on this page. If you object to any of the changes to the Privacy Policy, you must immediately cease using the Service and you can request that we remove your Personal Data, by contacting us through the contact information below. Unless stated otherwise, the then-current Privacy Policy applies to all data we have.</p>

                            <p className="mb-0">Contact Us</p>
                            <p>If you have any questions about this Privacy Policy, please contact us:</p>

                            <label htmlFor="">By email: <a href="mailto:admin@goodbit101.com">admin@goodbit101.com</a></label>

                            <address>
                                By mail: <br></br>
                                Goodbit, PBC <br></br>
                                1771 Highland Pl. Apt. 306 <br></br>
                                Berkeley, California 94709 <br></br>
                                United States of America
                            </address>

                        </div>
                    </div>
                </div>
            </section>
        );
    }
    componentDidMount(){
        document.title = "Privacy Policy| Goodbit101";
    }
}

export default PrivacyPolicy;
