import React, { Component } from "react";
// import { Link } from "react-router-dom";
import "./TermsOfServices.scss";
class TermsOfServices extends Component {
    render() {
        return (
            <section className="gb-tems-block">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-10 offset-lg-1">
                            <h1>Goodbit Terms of Service</h1>
                            <span className="gb-terms-date">Effective Date:  May 26, 2018</span>

                            <p>THIS IS A LEGALLY BINDING AGREEMENT THAT AFFECTS YOUR RIGHTS AND LIMITS OUR LIABILITY.  PLEASE READ IT CAREFULLY. BY USING OUR SITE, YOU ARE CONFIRMING YOUR AGREEMENT WITH THESE TERMS.  IF YOU DO NOT AGREE TO THE TERMS DESCRIBED HEREIN, YOU MUST LEAVE OUR SITE IMMEDIATELY.</p>
                            <p>This Terms of Service Agreement (“Terms of Service” or "Terms") is a legal agreement between you and Goodbit, PBC doing business as Goodbit101.com (“Goodbit,” “we” or “us”), and governs how you may use our website (“Site”) and any additional websites or mobile or desktop applications we may develop following the effective date of these Terms of Service.  When you browse our Site or use our app (the "App"), you are confirming your understanding of and agreement with these Terms of Service.  All references to the Site in these Terms also refer to the App.  For all questions about how we use the information we obtain through your use of the Site, please review our <a href="https://www.upfolio.com/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a>. By using the Site, you agree to also be bound to the Privacy Policy, the terms of which are incorporated herein by this reference. Any rights not expressly granted herein are expressly reserved by Goodbit.</p>
                            <p>NOTE: THIS SITE IS NOT INTENDED FOR USE BY CHILDREN UNDER THE AGE OF 13.  By using this site, you are confirming that you are above the age of 13.</p>
                            <p>1. DISCLAIMER. Goodbit offers digital currency (cryptocurrency) articles, price information, charts, investment articles, portfolio tracking tools, portfolio performance trackers, opinions, user comments, charts, etc.  All written copy, images, audio or video recordings, and any other information on this Site shall henceforth be referred to as “Content”. This Site is for informational and entertainment purposes only, and any Content published on this Site (including any advice, guidance, comments, or recommendations) is provided solely for that purpose. </p>
                            <p>The Site may from time to time include Content concerning financial, investment, tax and legal information, products, or services. However, we do not provide financial, investment, legal or tax advice. We are not a broker/dealer and we are not an investment advisor. All Content is not, and should not be regarded as “investment advice” or as a “recommendation” regarding a course of action, including without limitation as those terms are used in any applicable law or regulation. Always consult a financial professional and a legal professional before adopting any suggestion contained in, drawing any inference from or taking any other action in reliance on any Content that addresses financial, investment, tax and legal issues. We are not responsible for any adverse consequences of any financial, investment, tax and legal decision made based on the Content, including without limitation any loss of profit, which may arise directly or indirectly from use of or reliance on such Content.</p>
                            <p>No Content constitutes a recommendation that any act or investment is suitable for any specific person. No Content constitutes - or should be understood as constituting - a recommendation to enter in any cryptocurrency or securities transactions or to engage in any investment strategies. Cryptocurrencies and securities are often highly volatile and thus are considered extremely risky investments. Trading cryptocurrencies and other financial assets can carry a high level of risk and may not be suitable for all investors. You may experience losses due to price changes, system failures, and other reasons. Therefore, you should not speculate with money that you cannot afford to lose, including but not limited to retirement savings, student loans, mortgages, credit card funds, bank loans, emergency funds, or funds required to pay for living expenses. You should always understand that past performance is not necessarily indicative of future performance.</p>
                            <p>Authors of Content, including but not limited to commenters and Site visitors posting opinions, may have undisclosed connections to a cryptocurrency or other financial assets.</p>
                            <p>NOTE: Product and service information included in any Content or articles (including product recommendations and reviews) represent our opinions, and may be based solely on online research, and not on our personal experience using the product or service.</p>
                            <p>NOTE: Much of the Content on this Site is user-generated or provided by third-parties and, as such, impossible for us to monitor. Much of the information on our Site about businesses, assets, market data, investment strategies, investments and investment opportunities is provided by our users and other third parties. Our Site acts as a mere conduit for this information, and we do not select, monitor, edit, modify, review, evaluate or otherwise oversee the information or the publication of user generated information and third-party information on our Site.</p>
                            <p>2. Affiliate Relationships. We maintain marketing affiliate relationships with many of the sellers whose products may be featured and reviewed on this Site, in our email newsletters social media posts, and any other method or manner of publication we choose. If you elect to purchase any products or services from those companies, we will receive compensation for having referred them to you. When such a relationship exists and is not obvious, it will be mentioned in the article discussing the product, for example in the footer. We offer no guarantees that any product descriptions, pricing, or any other information about a product or service discussed on this Site, regardless of its source, is accurate, complete, reliable, current, or error-free. Site Content is provided for informational and entertainment purposes only and does not constitute an endorsement by Goodbit of any participating retailer. Goodbit assumes no liability for inaccuracy or incompleteness of any Content on the Site or in any communications from us.</p>
                            <p>3. Trademark &amp; Copyright. The trademarks, service marks, logos, and all written Content (collectively, "Protected Content") used and displayed on this Site are registered and unregistered marks of Goodbit and others, or are otherwise protected by copyright laws. Nothing on this Site should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark without our prior, written permission.</p>
                            <p>Goodbit hereby grants you a non-exclusive, non-transferable, revocable, limited license to access and use the Site under the terms set forth below.  The Site and the Content, including, but not limited to, text, data, reports, opinions, software (including HTML-based computer programs), images, photos, graphics, graphs, charts, animations and video displayed on the Site may be used only for your personal and non-commercial use. Except as otherwise permitted under these Terms of Service, you agree not to copy, reproduce, modify, create derivative works from, or store any Content, in whole or in part, from the Site or to display, perform, publish, distribute, transmit, broadcast or circulate any Content to anyone, or for any commercial purpose, without the express prior written consent of Goodbit. If you do choose to post a review, or to provide any other Content for publication on our Site (including, but not limited to, testimonials, comments, opinions, and endorsements), you agree that we may copy, distribute, display, publish, modify or translate your Content for any purpose and in any medium worldwide without any obligation to compensate you or any other third party in any way for any such use.  Such license that you are granting is royalty-free, perpetual, irrevocable and fully sub-licensable.</p>
                            <p>4. Termination of License. Goodbit reserves the right to terminate the License granted herein and deny you access to the Service (or any portion of the Site) in its sole discretion, without any advance notice or liability to you and liability if it believes your conduct fails to conform with these Terms of Service or for any other reason. Goodbit also reserves the right to investigate suspected violations of these Terms of Service, including, without limitation, any violation arising from any e-mails you send to Goodbit. Any violation of these Terms of Service may be referred to law enforcement authorities. The termination of your License and account will not affect any additional right or relief to which Goodbit may be entitled, at law or in equity. Upon termination of these Terms, all rights granted to you will automatically terminate and immediately revert to Goodbit.</p>
                            <p>5. General Prohibitions. You may not do any of the following:</p>

                            <ul className="gb-alpha">
                                <li>Copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code of the Site;</li>
                                <li>Remove or obscure the copyright notice or other notices displayed in connection with the Content accessible through the Site;</li>
                                <li>Interfere with or disrupt the Site, or servers and networks connected to the Site, or circumvent, disable or otherwise interfere with security-related features of the Site or features that prevent or restrict use or copying of any Content or that enforce limitations on use of the Site;</li>
                                <li>Modify the Site in any manner or form, or use modified versions thereof;</li>
                                <li>Sell, assign, sublicense, or otherwise transfer any right in the Content accessible through the Site;</li>
                                <li>Use any robot, spider, scraper, or other automated means to access the Service for any purpose;</li>
                                <li>Take any action that imposes or may impose an unreasonable or disproportionately large load on the Goodbit infrastructure as we may determine in our sole discretion;</li>
                                <li>Knowingly disseminate or transmit any worms, viruses or other harmful, disruptive or destructive files, code, programs or other similar technologies, or otherwise utilize the Service in any manner that violates any statute, rule, or regulation;</li>

                                <ul className="gb-roman">
                                    <li>Use more than one account.</li>
                                    <li>Violate any of the Usage Guidelines listed in the next section.</li>
                                </ul>
                            </ul>

                            <p>6. Usage Guidelines.  When using the Site, you agree to comply with the following guidelines, and to not use the Site to:</p>
                            <ul>
                                <li>Post any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, hateful, degrades others on the basis of gender, race, class, ethnicity, national origin, religion, sexual preference, disability or other classification or otherwise objectionable in any way or for any reason, according to our sole and absolute discretion;</li>
                                <li>Harm, threaten, or otherwise harass any other person or entity;</li>
                                <li>Post any unsolicited or unauthorized advertising or promotional materials, including (but not limited to) links to third party websites in comments or posts;</li>
                                <li>Disseminate or transmit any Content that (i) violates any law (whether local, state, national, or international), (ii) infringes or violates any copyright, trademark, trade secret, patent or any other proprietary right (including, but not limited to, using third party copyrighted materials or trademarks without appropriate permission or attribution), or (iii) includes third party information (whether or not protected as a trade secret) in violation of a duty of confidentiality;</li>
                                <li>Disseminate or transmit any worms, viruses or other harmful, disruptive or destructive files, code, programs or other similar technologies; or post any material that contains software viruses or any other computer code, files, programs or other similar technologies designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
                                <li>Post any Content that would violate the personal privacy rights of others, including but not limited to revealing personal or private information about others without their permission; </li>
                                <li>Impersonate any other person or entity; or</li>
                                <li>Facilitate violations of these Terms of Service or our Privacy Policy.</li>
                            </ul>

                            <p>Despite these prohibitions and guidelines, you understand that the Site is open for posting to all users. Some people may post Content and comments that are offensive, vulgar, objectionable, false, misleading, or inappropriate. You are responsible for your own Content.</p>
                            <p>We have the right to review, remove, preserve, and disclose any Content in order to a) comply with the law or b) enforce these Terms.</p>
                            <p>7. Advertisements and Links. The Site contains advertisements, offers, or other links to websites of third parties that we do not control. Any outbound links are provided solely for your reference, and are not to be viewed as an authorization, endorsement, sponsorship, or affiliation by, of, or with such website.  Note that advertisements and other information provided by third parties may not be wholly accurate, and Goodbit makes no representations whatsoever concerning such websites, or any products or services they may offer, and hereby disclaims any and all such representations.  Any purchase transactions or other dealings with third parties referenced on this Site, including payment and delivery of purchased items, are solely between yourself and them.  We are not responsible or liable for (i) the availability or accuracy of such websites or advertisements; or (ii) the Content, products or services available from such sites. ANY VISITS TO WEBSITES THAT LINK TO OR ADVERTISE ON THIS SITE ARE AT YOUR OWN RISK.</p>
                            <p>8. No Warranty. THE SITE IS PROVIDED “AS IS” WITHOUT ANY WARRANTIES OF ANY KIND. GOODBIT MAKES NO GUARANTEES OR WARRANTIES AS TO THE ACCURACY, COMPLETENESS, TIMELINESS OR CURRENTNESS OF ANY INFORMATION DISPLAYED ON THE SITE, AND HEREBY DISCLAIMS ANY AND ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, FREEDOM FROM COMPUTER VIRUS, AND WARRANTIES ARISING FROM COURSE OF DEALING OR COURSE OF PERFORMANCE. WE DO NOT REPRESENT OR WARRANT THAT THE FUNCTIONS CONTAINED IN THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVER THAT MAKES THE SITE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT MAKE ANY WARRANTIES OR REPRESENTATIONS REGARDING THE USE OF THE CONTENT OR COMMUNICATIONS IN THE SITE IN TERMS OF THEIR COMPLETENESS, CORRECTNESS, ACCURACY, ADEQUACY, USEFULNESS, TIMELINESS, RELIABILITY OR OTHERWISE.</p>
                            <p>Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion may not apply to you.</p>
                            <p>9. Limitation of Liability and Release.  In no event shall Goodbit be liable to you or any other party for any direct, indirect, special, incidental, consequential, exemplary, or punitive damages, however and wherever arising, that may result from your use of the Site, including without limitation to losses incurred due to: (a) any inaccurate information published on the site or any site accessible via an advertisement or link; (b) your business dealings with any third party advertisers or marketing affiliates that link to this site; (c) damages or losses of any kind, including, without limitation, injuries or death, resulting from your purchase and use of any products purchased from marketing affiliates or advertisers; (d) any actions you take in reliance upon any information provided by the Site; and (e) any other damages or losses you may incur in connection with your use of the Site.  IN NO EVENT WILL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OR ACTION EXCEED TEN UNITED STATES DOLLARS ($10.00).</p>
                            <p>Goodbit is not responsible for examining or evaluating the business practices, actions, omissions, or services of marketing affiliates, advertisers, companies, and third parties whose information, products, or services are featured on this Site. IN THE EVENT OF A DISPUTE BETWEEN YOU AND A MARKETING AFFILIATE, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU RELEASE GOODBIT, ITS SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND LEGAL REPRESENTATIVES FROM AND AGAINST CLAIMS AND DAMAGES OF ANY KIND, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH A DISPUTE.</p>
                            <p>If you are a California resident, by using the Site, you explicitly waive the rights granted to you under California Civil Code 1542, which states: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."  If you are a New Jersey resident, certain sections of these Terms of Service, including Sections 5, 6, and 7 may not apply to you pursuant to the New Jersey Truth in Consumer Contract, Warranty, and Notice Act.  Additional states may not allow this exclusion or limitation of liability, so the above limitation or exclusion may not apply to you.</p>
                            <p>10. Indemnification.  BY USING THE SITE, YOU AGREE TO DEFEND, INDEMNIFY AND HOLD HARMLESS GOODBIT AND ITS OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, LICENSORS, AND SERVICE OR CONTENT PROVIDERS FROM AND AGAINST ANY AND ALL LOSSES, LIABILITIES, EXPENSES, DAMAGES AND COSTS, INCLUDING REASONABLE ATTORNEYS’ FEES AND COURT COSTS, ARISING OR RESULTING FROM YOUR USE OF THE SITE AND ANY VIOLATION OF THESE TERMS OF USE. IF YOU CAUSE A TECHNICAL DISRUPTION OF THE SITE OR THE SYSTEMS TRANSMITTING THE SITE TO YOU OR OTHERS, YOU AGREE TO BE RESPONSIBLE FOR ANY AND ALL LOSSES, LIABILITIES, EXPENSES, DAMAGES AND COSTS, INCLUDING REASONABLE ATTORNEYS’ FEES AND COURT COSTS, ARISING OR RESULTING FROM THAT DISRUPTION.</p>
                            <p>11. Copyright.  All information and Content on this Site and any intellectual property rights embodied therein are the property of Goodbit (in the case of products discussed herein) or the manufacturers or sellers or those products.  Unless otherwise stated herein, none of the Content may be copied, reproduced, modified, distributed, sold, broadcast, stored or otherwise used without the express permission of Goodbit or the original copyright holder. You may display and print Content available on this Site solely for your personal, non-commercial use, provided that you do not modify the Content and that you retain all copyright and other proprietary notices contained in the Content. Unauthorized use of Content contained on this site is expressly prohibited by law, and may result in severe civil and criminal penalties.</p>
                            <p>12. COPYRIGHT COMPLAINTS AND COPYRIGHT AGENT.  If you discover that someone else has posted material belonging to you via the Site without your permission, please note the following.</p>
                            <ul>
                                <li>Termination of Repeat Infringer Accounts.  We respect the intellectual property rights of others and request that the users do the same.  Pursuant to 17 U.S.C. 512(i) of the United States Copyright Act, we have adopted and implemented a policy that provides for the termination in appropriate circumstances of users of the Site who are repeat infringers.  We may terminate access for participants or users who are found repeatedly to provide or post protected third party content without necessary rights and permissions.</li>
                                <li>DMCA Take-Down Notices.  If you’re a copyright owner or an agent thereof and believe, in good faith, that any materials provided on the Site infringe upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (see 17 U.S.C 512) (“DMCA”) by sending the following information in writing to our designated copyright agent as follows:</li>
                                <address>Zachary Jordan<br></br>Goodbit, PBC<br></br>1771 Highland Pl. Apt. 306<br></br>Berkeley, CA 94709</address>
                                <label htmlFor=""><span>Email:</span> <a href="mailto:Zack@goodbit101.com">Zack@goodbit101.com</a></label>

                                <ul className="gb-number">
                                    <li>The date of your notification; </li>
                                    <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
                                    <li>A description of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Site are covered by a single notification, a representative list of such works at the Site;</li>
                                    <li>A description of the material that is claimed to be infringing or to be the subject of infringing activity and information sufficient to enable us to locate such work;</li>
                                    <li>Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and/or email address;</li>
                                    <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
                                    <li>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
                                </ul>

                                <li>Counter-Notices. If you believe that your User Content that has been removed from the Site is not infringing, or that you have the authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use your Content, you may send a counter-notice containing the following information to our copyright agent using the contact information set forth above:</li>

                                <ul className="gb-number">
                                    <li>Your physical or electronic signature;</li>
                                    <li>A description of the Content that has been removed and the location at which the Content appeared before it was removed; </li>
                                    <li>A statement that you have a good faith belief that the Content was removed as a result of mistake or a misidentification of the Content; and</li>
                                    <li>Your name, address, telephone number, and email address, a statement that you consent to the jurisdiction of the federal court in Massachusetts and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</li>
                                </ul>

                            </ul>

                            <p>If a counter-notice is received by our copyright agent, we may send a copy of the counter-notice to the original complaining party informing such person that it may reinstate the removed Content in 10 business days.  Unless the copyright owner files an action seeking a court order against the Content provider, member or user, the removed Content may (in our discretion) be reinstated on the Site in 10 to 14 business days or more after receipt of the counter-notice.</p>
                            <p>13. Choice of Law; Forum. This document shall be governed in all respects by the laws of the United States and the State of Delaware, regardless of conflict of law rules. Any claim or dispute you may have against us, whether subject to mandatory arbitration or otherwise, must be brought in Dover, Delaware, except that arbitration proceedings may be conducted by telephone.  For any matters not subject to mandatory arbitration, you agree to submit to the personal jurisdiction of the courts located within Kent County, DE for the purpose of litigating all such claims or disputes.</p>
                            <p>All claims filed or brought contrary to this section shall be considered improperly filed. Should you file a claim improperly, we may recover reasonable attorneys’ fees and costs, provided that we have notified you in writing of the improperly filed claim and you have failed to withdraw the claim promptly.</p>
                            <p>14. Arbitration Agreement and Class Action Waiver. You agree to arbitrate all disputes and claims that arise out of or relate to your use of the Service. Therefore, you agree that, by using the Service, YOU ARE WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN ANY CLASS ACTION BASED ON OR INVOLVING CLAIMS BROUGHT IN A PURPORTED REPRESENTATIVE CAPACITY ON BEHALF OF THE GENERAL PUBLIC, OTHER USERS, OR PERSONS SIMILARLY SITUATED. This agreement to arbitrate includes, without limitation, claims arising out of or relating to the Service or your use thereof, regardless of when they may arise.  Any arbitration proceeding brought under this section shall be conducted by an arbitration service provider chosen by Goodbit applying Delaware law.  The arbitration may be conducted telephonically, with the costs to be split evenly between the parties.</p>
                            <p>15. Limitation of Actions.  Any claim or cause of action arising out of your use of the Site or Service must be filed within one year after such claim or cause of action arose or it shall forever be barred, notwithstanding any statute of limitations or other law to the contrary. Within this period, any failure by Goodbit to enforce or exercise any provision of these Terms of Service or any related right shall not constitute a waiver of that right or provision.</p>
                            <p>16. Modification and Notice of Changes.  Goodbit reserves the right to modify these Terms of Service at any time.  If we elect to modify these Terms, we will post a notice informing users of the change on the Site.  You are responsible for reviewing the modified Terms of Service, and accessing this Site after any changes to these Terms have been posted thereon will constitute your acceptance of all such changes. You have the right to accept or reject any changes in these Terms. If you reject any changes in these Terms, please discontinue use of the Site immediately. Unless specifically stated otherwise, any new features, products or services added to the Site shall be subject to these Terms. Some new products or features may require your acceptance of new or additional terms before use.</p>
                            <p>17. Entire Agreement. This Terms of Service and any document incorporated by reference herein constitute the entire agreement between you and us and govern your use of the Service, superseding any prior agreements between us.</p>
                            <p>18. Severability. If any provision of these Terms of Service is found by a court or other binding authority to be invalid, the remaining provisions shall continue in full force and effect.</p>
                            <p>If you have any questions or concerns regarding these Terms of Service, please contact us.</p>

                            <label htmlFor="">By email: <a href="mailto:Admin@goodbit101.com">Admin@goodbit101.com</a></label>
                            <address>
                                By mail:<br></br>Goodbit, PBC<br></br>1771 Highland Pl. Apt. 306<br></br>Berkeley, CA 94709
                            </address>

                        </div>
                    </div>
                </div>
            </section>
        );
    }
    componentDidMount(){
        document.title = "Terms of services| Goodbit101";
    }
}

export default TermsOfServices;
